{"timestamp":"2025-09-24T16:43:26.185362","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-24T16:43:26.185996","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/evaluate_and_promote_to_staging_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-24T16:43:27.577004Z","level":"info","event":"Staging 후보 평가 프로세스를 시작합니다.","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-24T16:43:30.754431","level":"warning","event":"Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb257f6b70>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:43:40.406310","level":"warning","event":"Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1f91f0b0>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:43:52.154372","level":"warning","event":"Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb38d39e50>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:44:13.682979","level":"warning","event":"Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1ee4baa0>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:44:50.594203","level":"warning","event":"Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1ee48530>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:46:02.049137","level":"warning","event":"Retrying (Retry(total=1, connect=1, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1ee4ba70>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:48:12.179329","level":"warning","event":"Retrying (Retry(total=0, connect=0, read=7, redirect=7, status=7)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1eea8380>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-24T16:48:15.308044","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"MlflowException","exc_value":"API request to http://mlflow:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1eea89b0>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/evaluate_and_promote_to_staging_dag.py","lineno":28,"name":"evaluate_and_promote_to_staging"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py","lineno":2896,"name":"search_runs"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py","lineno":1926,"name":"get_experiment_by_name"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py","lineno":1770,"name":"get_experiment_by_name"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py","lineno":279,"name":"get_experiment_by_name"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py","lineno":855,"name":"get_experiment_by_name"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py","lineno":200,"name":"_call_endpoint"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py","lineno":549,"name":"call_endpoint"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py","lineno":253,"name":"http_request"}],"is_group":false,"exceptions":[]},{"exc_type":"ConnectionError","exc_value":"HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1eea89b0>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py","lineno":230,"name":"http_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/request_utils.py","lineno":237,"name":"_get_http_response_with_retries"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":677,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=credit_fraud_experiment (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x75eb1eea89b0>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":644,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x75eb1eea89b0>: Failed to resolve 'mlflow' ([Errno -2] Name or service not known)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -2] Name or service not known","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
